services:
  f12-rifas:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: 1000
    image: php:8.4-fpm
    container_name: f12-rifas
    restart: unless-stopped
    environment:
      APP_ENV: production
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/default.conf:/etc/nginx/sites-available/default
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./certificates:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql
      - redis
    networks:
      - f12net

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql-data:/var/lib/mysql
    # ports:
    #   - "3306:3306"
    expose:
      - "3306"
    networks:
      - f12net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    # ports:
    #   - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - f12net

#   certbot:
#     image: certbot/certbot
#     container_name: certbot
#     volumes:
#       - ../:/var/www/html
#       - ./certificates:/etc/letsencrypt
#     entrypoint: "/bin/sh -c"
#     command: >
#       "certbot certonly --webroot -w /var/www/html/public
#       --email mr.robot.felipe@gmail.com --agree-tos --no-eff-email
#       -d f12rifas.com.br --rsa-key-size 4096 --force-renewal"
#     networks:
#       - f12net

volumes:
  mysql-data:
  redis-data:

networks:
  f12net:
    driver: bridge
