services:
  f12-rifas:
    image: ghcr.io/felipeatari/f12-rifas:latest
    container_name: f12-rifas
    restart: unless-stopped
    environment:
      APP_ENV: production
    volumes:
        # - /root/f12-rifas/.env:/var/www/html/.env:ro
        - ../:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: mysql-prod
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    container_name: redis-prod
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mysql-data:
