name: CI/CD Laravel Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Define image tag
      id: vars
      run: echo "IMAGE_TAG=build-$(date +%s)" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/f12-rifas:${{ env.IMAGE_TAG }}
        docker build -t $IMAGE_NAME -f docker/Dockerfile .
        docker push $IMAGE_NAME

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        script: |
          IMAGE_TAG=${{ env.IMAGE_TAG }}
          IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/f12-rifas:$IMAGE_TAG

          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

          cd /root/f12-rifas/docker

          echo "Atualizando tag da imagem no docker-compose.yml..."
          sed -i "s|image: ghcr.io/.*/f12-rifas:.*|image: $IMAGE_NAME|" docker-compose.yml

          docker compose down --volumes --remove-orphans
          docker pull $IMAGE_NAME
          docker compose up -d --remove-orphans

          echo "Aguardando MySQL ficar pronto..."
          sleep 30

          docker exec f12-rifas php artisan migrate --force
