name: CI/CD Laravel Docker Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Copiar .env
      run: cp .env.example .env

    - name: Build da imagem Docker para testes
      run: docker build -t f12-rifas-test -f docker/Dockerfile .

    - name: Instalar dependências no container
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app f12-rifas-test \
        composer install --no-interaction --prefer-dist --no-scripts --no-progress

    - name: Gerar chave da aplicação
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app f12-rifas-test \
        php artisan key:generate

    - name: Ajustar permissões
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app f12-rifas-test \
        chmod -R 777 storage bootstrap/cache

    - name: Criar banco SQLite
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Rodar testes dentro do container
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -w /app \
        -e DB_CONNECTION=sqlite \
        -e DB_DATABASE=database/database.sqlite \
        f12-rifas-test php artisan test

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login no GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build e push da imagem para produção
      run: |
        IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/f12-rifas:latest
        docker build -t $IMAGE_NAME -f docker/Dockerfile .
        docker push $IMAGE_NAME

    - name: Deploy remoto via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        script: |
          cd /caminho/para/seu/projeto
          docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/f12-rifas:latest
          docker compose -f docker/docker-compose.yml down
          docker compose -f docker/docker-compose.yml up -d --build
          docker compose -f docker/docker-compose.yml exec app php artisan migrate --force
