name: CI/CD Laravel Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker image
      run: |
        TAG=build-${{ github.run_number }}
        IMAGE=ghcr.io/${{ secrets.GHCR_USERNAME }}/f12-rifas
        docker build -t $IMAGE:$TAG -t $IMAGE:latest -f docker/Dockerfile docker/
        docker push $IMAGE:$TAG
        docker push $IMAGE:latest
        echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        script: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin

          cd /root/f12-rifas/docker

          echo "Exportando variáveis e substituindo no docker-compose..."
          export IMAGE_TAG=${{ env.IMAGE_TAG }}
          envsubst < docker-compose.yml > docker-compose.generated.yml

          docker compose -f docker-compose.generated.yml stop f12-rifas
          docker rm -f f12-rifas
          docker pull ghcr.io/felipeatari/f12-rifa:$IMAGE_TAG
          docker compose -f docker-compose.generated.yml up -d f12-rifas

          echo "Aguardando MySQL ficar pronto..."
          sleep 20

          docker exec f12-rifas php artisan migrate --force
