name: CI/CD Laravel Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/f12-rifas
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        script: |
          docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/f12-rifas
          docker stop f12-rifas || true
          docker rm f12-rifas || true
          docker run -d --name f12-rifas -p 80:80 ghcr.io/${{ secrets.GHCR_USERNAME }}/f12-rifas
