name: CI/CD Laravel Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ secrets.GHCR_USERNAME }}/f12-rifas:latest
        docker build -t $IMAGE_NAME -f docker/Dockerfile docker/
        docker push $IMAGE_NAME

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        script: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin

          cd /root/f12-rifas/docker

          docker compose down --volumes --remove-orphans
          docker image rm $IMAGE_NAME || true
          docker pull $IMAGE_NAME
          docker compose up -d --build

          echo "Aguardando MySQL ficar pronto..."
          sleep 30

          docker exec f12-rifas php artisan migrate --force

